name: Deploy Fullstack App to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1. 프론트엔드 빌드
      - name: Build Frontend
        working-directory: ./board-app
        run: |
          npm install
          VITE_API_URL=/api/boards npm run build

      # 2. EC2로 파일 전송
      - name: Deploy to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "board-app/dist/*,board-backend/*"
          target: ${{ secrets.EC2_TARGET_DIR }}

      # 3. 서버에서 환경 변수 설정 및 실행
      - name: Executing remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ${{ secrets.EC2_TARGET_DIR }}/board-backend
            
            echo "DB_HOST=localhost" > .env
            echo "DB_PORT=3306" >> .env
            echo "DB_USER=root" >> .env
            echo "DB_PASSWORD=1234" >> .env
            echo "DB_NAME=myDb" >> .env
            echo "PORT=5000" >> .env
            
            npm install
            pm2 delete board-api || true
            pm2 start src/server.js --name board-api
